export const list = {
    "10.9": [
        "Ngô Võ Ngọc Hoàng Anh",
        "Nguyễn Hà Kiều Anh",
        "Nguyễn Thị Quỳnh Anh",
        "Nguyễn Phạm Quân Bảo",
        "Nguyễn Trần Gia Bảo",
        "Nguyễn Thanh Bình",
        "Nguyễn Ngọc Minh Châu",
        "Phạm Văn Anh Đức",
        "Nguyễn Thái Thanh Hà",
        "Nguyễn Thanh Hằng",
        "Lê Trần Gia Hân",
        "Lê Hoàng",
        "Nguyễn Huy Hoàng",
        "Đinh Hữu Gia Huy",
        "Bùi Quỳnh Hương",
        "Lê Ngọc Đăng Khoa",
        "Trương Tuấn Kiệt",
        "Nguyễn Thanh Liêm",
        "Đỗ Hoàng Linh",
        "Trần Khánh Linh",
        "Trần Nguyễn Nhật Linh",
        "Nguyễn Ngọc Minh",
        "Đinh Thị Trà My",
        "Nguyễn Kim Ngân",
        "Nguyễn Lê Thảo Nguyên",
        "Nguyễn Thị Minh Nguyện",
        "Lương Thị Yến Nhi",
        "Phan Tuyết Nhung",
        "Trần Nguyễn Tuyết Như",
        "Ngô Duy Phước",
        "Trương Đan Quý",
        "Đỗ Thị Như Quỳnh",
        "Nguyễn Phạm Quyền Thái",
        "Lưu Ngọc Thanh Thảo",
        "Phan Công Thọ",
        "Nguyễn Phương Thùy",
        "Nguyễn Đào Minh Thư",
        "Hoàng Đình Anh Thy",
        "Đỗ Quỳnh Trang",
        "Nguyễn Thị Mai Trang",
        "Bùi Nguyễn Tiến Trường",
        "Nguyễn Ngọc Anh Tuấn",
        "Lê Nguyễn Tú Uyên",
        "Lê Ngọc Tường Vy",
        "Quách Thị Mai Xuân",
    ],
    "10.11": [
        "Trần Thế An",
        "Đào Ngọc Quỳnh Anh",
        "Nguyễn Thị Lan Anh",
        "Nguyễn Xuân Quốc Anh",
        "Nguyễn Thái Bình",
        "Trần Thị Ngọc Diễm",
        "Lê Hồng Bách Diệp",
        "Quách Tuấn Dũng",
        "Võ Nguyễn Thảo Duyên",
        "Nguyễn Tiến Đạt",
        "Vũ Thị Hồng Hạnh",
        "Phạm Huỳnh Ngọc Hân",
        "Tống Văn Hiếu",
        "Nguyễn Việt Hoàng",
        "Nguyễn Bùi Bảo Huy",
        "Nguyễn Thị Ngân Hương",
        "Nguyễn Văn Thành Khôi",
        "Nguyễn Thị Thùy Linh",
        "Nguyễn Hoàng Nhật Luân",
        "Nguyễn Phúc Xuân Mai",
        "Lê Phạm Hà My",
        "Đặng Thị Thúy Nga",
        "Ngô Thị Kim Ngọc",
        "Trương Bảo Ngọc",
        "Lê Khôi Nguyên",
        "Bùi Thị Yến Nhi",
        "Phạm Yến Nhi",
        "Trần Thị Ý Nhi",
        "Ừng Ngọc Như",
        "Trần Minh Quân",
        "Vũ Ngọc Như Quỳnh",
        "Phạm Hoàng Thái",
        "Phạm Thanh Thảo",
        "Lê Quỳnh Thư",
        "Lê Thị Anh Thư",
        "Kiều Thủy Tiên",
        "Võ Đình Toán",
        "Hà Thị Huyền Trang",
        "Mai Đức Trọng",
        "Hồ Ngọc Thanh Trúc",
        "Nguyễn Thành Trung",
        "Nguyễn Nam Thanh Tú",
        "Cấn Nguyễn Khánh Vân",
        "Phạm Anh Thảo Vy",
        "Nguyễn Thị Hải Yến",
    ],
    "11.4": [
        "Hoàng Hải Anh",
        "Phan Ngọc Quỳnh Anh",
        "Trần Lê Tuấn Anh",
        "Nguyễn Huỳnh Mỹ Chi",
        "Văn Thị Thùy Dung",
        "Bùi Vũ Đức Dương",
        "Phạm Nguyễn Thụy Chương Đài",
        "Hoàng Đan",
        "Nguyễn Minh Đức",
        "Nguyễn Tất Hoàng",
        "Lê Nhân Huy",
        "Nông Thị Ngọc Huyền",
        "Phạm Xuân Khánh",
        "Nguyễn Như Kiên",
        "Nguyễn Thị Lan",
        "Nguyễn Thị Ngọc Linh",
        "Phạm Ngọc Khánh Linh",
        "Phan Huy Long",
        "Đặng Minh Phúc Lộc",
        "Ngô Huỳnh Thảo Ly",
        "Nguyễn Thị Thanh Mai",
        "Nguyễn Hữu Trà Mi",
        "Nguyễn Huỳnh Giáng My",
        "Nguyễn Văn Nam",
        "Đậu Phan Kim Ngân",
        "Trần Dương Đại Nghĩa",
        "Châu Yến Ngọc",
        "Lý Yến Nhi",
        "Phạm Hồng Nhi",
        "Đặng Nguyễn Quỳnh Như",
        "Trần Phan Ngọc Phú",
        "Nguyễn Hữu Hoàng Phúc",
        "Trịnh Minh Quân",
        "Võ Nguyệt Quế",
        "Trần Phan Ngọc Quý",
        "Trần Thị Tố Quyên",
        "Nguyễn Thị Thúy Quỳnh",
        "Đinh Thái Sơn",
        "Nguyễn Thị Thanh Thùy",
        "Huỳnh Nguyễn Anh Thư",
        "Nguyễn Ngọc Quỳnh Thy",
        "Nguyễn Đỗ Thùy Trang",
        "Phạm Nguyễn Thành Trung",
        "Lê Hoàng Vũ",
    ],
};
